name: docker

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cash-machine
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Setup faas-cli
        run: curl -sSL https://cli.openfaas.com | sh
        
      - name: Shrink wrap code
        run: ./faas-cli build --shrinkwrap -f cash-machine.yml
          
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin
          
      - name: Run Buildx
        run: docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t karlheinzkurt/cash-machine:latest \
            --file build/cash-machine/Dockerfile \
            --push
            build/cash-machine
            
